apiVersion: v1
data:
  .dockercfg: { { .Values.global.registry.dockercfg } }
kind: Secret
metadata:
  name: docker-key
  labels: { { - include "codeanker.label" . | indent 4 } }
type: kubernetes.io/dockercfg
