version: "3"
services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
      target: base
    tty: true
    command: npm run dev -w ./frontend
    environment:
      - VITE_APP_API_URL=http://api:3030
    ports:
      - 8080:8080
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./packages:/app/packages
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
      target: base
    command: npm run dev -w ./api
    ports:
      - 3030:3030
    volumes:
      - ./api/src:/app/api/src
      - ./api/prisma:/app/api/prisma
    environment:
      - NODE_ENV=docker
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/brahmsee.digital?schema=public
