version: "3.9"

services:
  web:
    build: .
    container_name: web
    environment:
      NODE_ENV: preview
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/brahmsee.digital?schema=public"
    ports:
      - 8085:8085

  postgres:
    image: postgres:15.3-alpine3.18
    container_name: postgres
    hostname: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brahmsee.digital
      TZ: Europe/Berlin
