version: "3"
services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
      target: base
    tty: true
    command: npm run dev -w ./frontend
    environment:
      - VITE_APP_API_URL=http://api:3030
    ports:
      - 8080:8080
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./packages:/app/packages
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
      target: base
    command: npm run dev -w ./api
    depends_on:
      - mongodb
    ports:
      - 3030:3030
      - 9999:9999
    volumes:
      - ./api/src:/app/api/src
      - ./api/data:/app/api/data
      - ./api/public:/app/api/public
      - ./api/config:/app/api/config
      - ./api/test:/app/api/test
    environment:
      - NODE_ENV=docker
  mongodb:
    image: mongo:6.0.5
    ports:
      - 27017:27017
    volumes:
       - mongodb-data:/data/db
volumes:
  mongodb-data:
