packages:
  - api/
  - frontend/
  - packages/*
catalog:
  typescript: ^5.7.2
  '@types/node': ^22.10.2
  eslint: ^9.17.0
  typescript-eslint: ^8.18.2
  '@eslint/js': ^9.17.0
  vue-tsc: ^2.2.0
  '@trpc/server': 11.0.0-rc.682
  '@trpc/client': 11.0.0-rc.682
