packages:
  - apps/*
  - packages/*
catalog:
  "@eslint/js": ^9.17.0
  "@tiptap/extension-document": ^2.11.0
  "@tiptap/extension-highlight": ^2.11.0
  "@tiptap/extension-link": ^2.11.0
  "@tiptap/extension-paragraph": ^2.11.0
  "@tiptap/extension-text": ^2.11.0
  "@tiptap/pm": ^2.11.0
  "@tiptap/starter-kit": ^2.11.0
  "@tiptap/vue-3": ^2.11.0
  "@trpc/client": 11.0.0-rc.682
  "@trpc/server": 11.0.0-rc.682
  "@types/node": ^22.10.2
  "eslint": ^9.17.0
  "superjson": ^2.2.2
  "typescript-eslint": ^8.18.2
  "typescript": ^5.7.2
  "vue-tsc": ^2.2.0
  "vue": ^3.5.13
  "zod": ^3.24.2
