packages:
  - apps/*
  - packages/*
catalog:
  "@azure/storage-blob": "^12.17.0"
  "@eslint/js": ^9.17.0
  "@faker-js/faker": "^10.1.0"
  "@tiptap/extension-document": ^2.11.0
  "@tiptap/extension-highlight": ^2.11.0
  "@tiptap/extension-link": ^2.11.0
  "@tiptap/extension-paragraph": ^2.11.0
  "@tiptap/extension-text": ^2.11.0
  "@tiptap/pm": ^2.11.0
  "@tiptap/starter-kit": ^2.11.0
  "@tiptap/vue-3": ^2.11.0
  "@trpc/client": 11.0.0-rc.682
  "@trpc/server": 11.0.0-rc.682
  "@types/node": ^22.10.2
  "eslint": ^9.39.1
  "superjson": ^2.2.2
  "typescript-eslint": ^8.27.0
  "typescript": ^5.7.2
  "vitest": ^3.1.1
  "vue-tsc": ^2.2.0
  "vue": ^3.5.13
