packages:
  - apps/*
  - packages/*
catalog:
  # project
  typescript: ^5.7.2
  '@types/node': ^22.10.2
  eslint: ^9.17.0
  typescript-eslint: ^8.18.2
  '@eslint/js': ^9.17.0
  vue-tsc: ^2.2.0
  # trpc
  '@trpc/server': 11.0.0-rc.682
  '@trpc/client': 11.0.0-rc.682
  superjson: ^2.2.2
  # tiptap
  '@tiptap/pm': '^2.11.0'
  '@tiptap/starter-kit': '^2.11.0'
  '@tiptap/vue-3': '^2.11.0'
  '@tiptap/extension-document': '^2.11.0'
  '@tiptap/extension-highlight': '^2.11.0'
  '@tiptap/extension-link': '^2.11.0'
  '@tiptap/extension-paragraph': '^2.11.0'
  '@tiptap/extension-text': '^2.11.0'
  # vue
  vue: ^3.5.13
