export const Countries = {
  DEU: {
    NAT: 'DEU',
    nameDE: 'Deutschland',
    name: 'Germany',
    ISO3: 'DEU',
    ISO: 'DE',
    independent: true,
    i18nKey: 'countries.deutschland',
  },
  AFG: {
    NAT: 'AFG',
    nameDE: 'Afghanistan',
    name: 'Afghanistan',
    ISO3: 'AFG',
    ISO: 'AF',
    independent: true,
    i18nKey: 'countries.afghanistan',
  },
  EGY: {
    NAT: 'EGY',
    nameDE: 'Ägypten',
    name: 'Egypt',
    ISO3: 'EGY',
    ISO: 'EG',
    independent: true,
    i18nKey: 'countries.aegypten',
  },
  ALA: {
    NAT: 'ALA',
    nameDE: 'Åland',
    name: 'Åland Islands',
    ISO3: 'ALA',
    ISO: 'AX',
    independent: false,
    i18nKey: 'countries.alandinseln',
  },
  ALB: {
    NAT: 'ALB',
    nameDE: 'Albanien',
    name: 'Albania',
    ISO3: 'ALB',
    ISO: 'AL',
    independent: true,
    i18nKey: 'countries.albanien',
  },
  DZA: {
    NAT: 'DZA',
    nameDE: 'Algerien',
    name: 'Algeria',
    ISO3: 'DZA',
    ISO: 'DZ',
    independent: true,
    i18nKey: 'countries.algerien',
  },
  VIR: {
    NAT: 'VIR',
    nameDE: 'Amerikanische Jungferninseln',
    name: 'Virgin Islands (U.S.)',
    ISO3: 'VIR',
    ISO: 'VI',
    independent: false,
    i18nKey: 'countries.amerikanische-jungferninseln',
  },
  ASM: {
    NAT: 'ASM',
    nameDE: 'Amerikanisch-Samoa',
    name: 'American Samoa',
    ISO3: 'ASM',
    ISO: 'AS',
    independent: false,
    i18nKey: 'countries.amerikanisch-samoa',
  },
  AND: {
    NAT: 'AND',
    nameDE: 'Andorra',
    name: 'Andorra',
    ISO3: 'AND',
    ISO: 'AD',
    independent: true,
    i18nKey: 'countries.andorra',
  },
  AGO: {
    NAT: 'AGO',
    nameDE: 'Angola',
    name: 'Angola',
    ISO3: 'AGO',
    ISO: 'AO',
    independent: true,
    i18nKey: 'countries.angola',
  },
  AIA: {
    NAT: 'AIA',
    nameDE: 'Anguilla',
    name: 'Anguilla',
    ISO3: 'AIA',
    ISO: 'AI',
    independent: false,
    i18nKey: 'countries.anguilla',
  },
  ATA: {
    NAT: 'ATA',
    nameDE: 'Antarktis',
    name: 'Antarctica',
    ISO3: 'ATA',
    ISO: 'AQ',
    independent: false,
    i18nKey: 'countries.antarktis',
  },
  ATG: {
    NAT: 'ATG',
    nameDE: 'Antigua und Barbuda',
    name: 'Antigua and Barbuda',
    ISO3: 'ATG',
    ISO: 'AG',
    independent: true,
    i18nKey: 'countries.antigua-und-barbuda',
  },
  GNQ: {
    NAT: 'GNQ',
    nameDE: 'Äquatorialguinea',
    name: 'Equatorial Guinea',
    ISO3: 'GNQ',
    ISO: 'GQ',
    independent: true,
    i18nKey: 'countries.aequatorialguinea',
  },
  ARG: {
    NAT: 'ARG',
    nameDE: 'Argentinien',
    name: 'Argentina',
    ISO3: 'ARG',
    ISO: 'AR',
    independent: true,
    i18nKey: 'countries.argentinien',
  },
  ARM: {
    NAT: 'ARM',
    nameDE: 'Armenien',
    name: 'Armenia',
    ISO3: 'ARM',
    ISO: 'AM',
    independent: true,
    i18nKey: 'countries.armenien',
  },
  ABW: {
    NAT: 'ABW',
    nameDE: 'Aruba',
    name: 'Aruba',
    ISO3: 'ABW',
    ISO: 'AW',
    independent: false,
    i18nKey: 'countries.aruba',
  },
  ETH: {
    NAT: 'ETH',
    nameDE: 'Äthiopien',
    name: 'Ethiopia',
    ISO3: 'ETH',
    ISO: 'ET',
    independent: true,
    i18nKey: 'countries.aethiopien',
  },
  AUS: {
    NAT: 'AUS',
    nameDE: 'Australien',
    name: 'Australia',
    ISO3: 'AUS',
    ISO: 'AU',
    independent: true,
    i18nKey: 'countries.australien',
  },
  AZE: {
    NAT: 'AZE',
    nameDE: 'Azerbaidschan',
    name: 'Azerbaijan',
    ISO3: 'AZE',
    ISO: 'AZ',
    independent: true,
    i18nKey: 'countries.aserbaidschan',
  },
  BHS: {
    NAT: 'BHS',
    nameDE: 'Bahamas',
    name: 'Bahamas',
    ISO3: 'BHS',
    ISO: 'BS',
    independent: true,
    i18nKey: 'countries.bahamas',
  },
  BHR: {
    NAT: 'BHR',
    nameDE: 'Bahrein',
    name: 'Bahrain',
    ISO3: 'BHR',
    ISO: 'BH',
    independent: true,
    i18nKey: 'countries.bahrain',
  },
  BGD: {
    NAT: 'BGD',
    nameDE: 'Bangladesch',
    name: 'Bangladesh',
    ISO3: 'BGD',
    ISO: 'BD',
    independent: true,
    i18nKey: 'countries.bangladesch',
  },
  BRB: {
    NAT: 'BRB',
    nameDE: 'Barbados',
    name: 'Barbados',
    ISO3: 'BRB',
    ISO: 'BB',
    independent: true,
    i18nKey: 'countries.barbados',
  },
  BEL: {
    NAT: 'BEL',
    nameDE: 'Belgien',
    name: 'Belgium',
    ISO3: 'BEL',
    ISO: 'BE',
    independent: true,
    i18nKey: 'countries.belgien',
  },
  BLZ: {
    NAT: 'BLZ',
    nameDE: 'Belize',
    name: 'Belize',
    ISO3: 'BLZ',
    ISO: 'BZ',
    independent: true,
    i18nKey: 'countries.belize',
  },
  BEN: {
    NAT: 'BEN',
    nameDE: 'Benin',
    name: 'Benin',
    ISO3: 'BEN',
    ISO: 'BJ',
    independent: true,
    i18nKey: 'countries.benin',
  },
  BMU: {
    NAT: 'BMU',
    nameDE: 'Bermuda',
    name: 'Bermuda',
    ISO3: 'BMU',
    ISO: 'BM',
    independent: false,
    i18nKey: 'countries.bermuda',
  },
  BTN: {
    NAT: 'BTN',
    nameDE: 'Bhutan',
    name: 'Bhutan',
    ISO3: 'BTN',
    ISO: 'BT',
    independent: true,
    i18nKey: 'countries.bhutan',
  },
  BOL: {
    NAT: 'BOL',
    nameDE: 'Bolivien',
    name: 'Bolivia',
    ISO3: 'BOL',
    ISO: 'BO',
    independent: true,
    i18nKey: 'countries.bolivien',
  },
  BES: {
    NAT: 'BES',
    nameDE: 'Bonaire, Saba, Sint Eustatius',
    name: 'Bonaire, Sint Eustatius and Saba',
    ISO3: 'BES',
    ISO: 'BQ',
    independent: false,
    i18nKey: 'countries.bonaire-sint-eustatius-und-saba',
  },
  BIH: {
    NAT: 'BIH',
    nameDE: 'Bosnien und Herzegowina',
    name: 'Bosnia and Herzegovina',
    ISO3: 'BIH',
    ISO: 'BA',
    independent: true,
    i18nKey: 'countries.bosnien-und-herzegowina',
  },
  BWA: {
    NAT: 'BWA',
    nameDE: 'Botswana',
    name: 'Botswana',
    ISO3: 'BWA',
    ISO: 'BW',
    independent: true,
    i18nKey: 'countries.botsuana',
  },
  BVT: {
    NAT: 'BVT',
    nameDE: 'Bouvetinsel',
    name: 'Bouvet Island',
    ISO3: 'BVT',
    ISO: 'BV',
    independent: false,
    i18nKey: 'countries.bouvetinsel',
  },
  BRA: {
    NAT: 'BRA',
    nameDE: 'Brasilien',
    name: 'Brazil',
    ISO3: 'BRA',
    ISO: 'BR',
    independent: true,
    i18nKey: 'countries.brasilien',
  },
  VGB: {
    NAT: 'VGB',
    nameDE: 'Britische Jungferninseln',
    name: 'Virgin Islands (British)',
    ISO3: 'VGB',
    ISO: 'VG',
    independent: false,
    i18nKey: 'countries.britische-jungferninseln',
  },
  IOT: {
    NAT: 'IOT',
    nameDE: 'Britisches Territorium im Indischen Ozean',
    name: 'British Indian Ocean Territory',
    ISO3: 'IOT',
    ISO: 'IO',
    independent: false,
    i18nKey: 'countries.britisches-territorium-im-indischen-ozean',
  },
  BRN: {
    NAT: 'BRN',
    nameDE: 'Brunei',
    name: 'Brunei',
    ISO3: 'BRN',
    ISO: 'BN',
    independent: true,
    i18nKey: 'countries.brunei-darussalam',
  },
  BGR: {
    NAT: 'BGR',
    nameDE: 'Bulgarien',
    name: 'Bulgaria',
    ISO3: 'BGR',
    ISO: 'BG',
    independent: true,
    i18nKey: 'countries.bulgarien',
  },
  BFA: {
    NAT: 'BFA',
    nameDE: 'Burkina Faso',
    name: 'Burkina Faso',
    ISO3: 'BFA',
    ISO: 'BF',
    independent: true,
    i18nKey: 'countries.burkina-faso',
  },
  BDI: {
    NAT: 'BDI',
    nameDE: 'Burundi',
    name: 'Burundi',
    ISO3: 'BDI',
    ISO: 'BI',
    independent: true,
    i18nKey: 'countries.burundi',
  },
  CYM: {
    NAT: 'CYM',
    nameDE: 'Cayman Islands (Kaimaninseln)',
    name: 'Cayman Islands',
    ISO3: 'CYM',
    ISO: 'KY',
    independent: false,
    i18nKey: 'countries.kaimaninseln',
  },
  CHL: {
    NAT: 'CHL',
    nameDE: 'Chile',
    name: 'Chile',
    ISO3: 'CHL',
    ISO: 'CL',
    independent: true,
    i18nKey: 'countries.chile',
  },
  CHN: {
    NAT: 'CHN',
    nameDE: 'China',
    name: 'China',
    ISO3: 'CHN',
    ISO: 'CN',
    independent: true,
    i18nKey: 'countries.china',
  },
  COK: {
    NAT: 'COK',
    nameDE: 'Cookinseln',
    name: 'Cook Islands',
    ISO3: 'COK',
    ISO: 'CK',
    independent: false,
    i18nKey: 'countries.cookinseln',
  },
  CRI: {
    NAT: 'CRI',
    nameDE: 'Costa Rica',
    name: 'Costa Rica',
    ISO3: 'CRI',
    ISO: 'CR',
    independent: true,
    i18nKey: 'countries.costa-rica',
  },
  CUW: {
    NAT: 'CUW',
    nameDE: 'Curaçao',
    name: 'Curaçao',
    ISO3: 'CUW',
    ISO: 'CW',
    independent: false,
    i18nKey: 'countries.curacao',
  },
  DNK: {
    NAT: 'DNK',
    nameDE: 'Dänemark',
    name: 'Denmark',
    ISO3: 'DNK',
    ISO: 'DK',
    independent: true,
    i18nKey: 'countries.daenemark',
  },
  COD: {
    NAT: 'COD',
    nameDE: 'Demokratische Republik Kongo',
    name: 'Congo, Democratic Republic of the',
    ISO3: 'COD',
    ISO: 'CD',
    independent: true,
    i18nKey: 'countries.demokratische-republik-kongo',
  },
  DMA: {
    NAT: 'DMA',
    nameDE: 'Dominica',
    name: 'Dominica',
    ISO3: 'DMA',
    ISO: 'DM',
    independent: true,
    i18nKey: 'countries.dominica',
  },
  DOM: {
    NAT: 'DOM',
    nameDE: 'Dominikanische Republik',
    name: 'Dominican Republic',
    ISO3: 'DOM',
    ISO: 'DO',
    independent: true,
    i18nKey: 'countries.dominikanische-republik',
  },
  DJI: {
    NAT: 'DJI',
    nameDE: 'Dschibuti',
    name: 'Djibouti',
    ISO3: 'DJI',
    ISO: 'DJ',
    independent: true,
    i18nKey: 'countries.dschibuti',
  },
  ECU: {
    NAT: 'ECU',
    nameDE: 'Ecuador',
    name: 'Ecuador',
    ISO3: 'ECU',
    ISO: 'EC',
    independent: true,
    i18nKey: 'countries.ecuador',
  },
  SLV: {
    NAT: 'SLV',
    nameDE: 'El Salvador',
    name: 'El Salvador',
    ISO3: 'SLV',
    ISO: 'SV',
    independent: true,
    i18nKey: 'countries.el-salvador',
  },
  CIV: {
    NAT: 'CIV',
    nameDE: 'Elfenbeinküste',
    name: "Côte d'Ivoire",
    ISO3: 'CIV',
    ISO: 'CI',
    independent: true,
    i18nKey: 'countries.elfenbeinkueste',
  },
  ERI: {
    NAT: 'ERI',
    nameDE: 'Eritrea',
    name: 'Eritrea',
    ISO3: 'ERI',
    ISO: 'ER',
    independent: true,
    i18nKey: 'countries.eritrea',
  },
  EST: {
    NAT: 'EST',
    nameDE: 'Estland',
    name: 'Estonia',
    ISO3: 'EST',
    ISO: 'EE',
    independent: true,
    i18nKey: 'countries.estland',
  },
  SWZ: {
    NAT: 'SWZ',
    nameDE: 'Eswatini (Swaziland)',
    name: 'Eswatini',
    ISO3: 'SWZ',
    ISO: 'SZ',
    independent: true,
    i18nKey: 'countries.swasiland',
  },
  LIE: {
    NAT: 'LIE',
    nameDE: 'F.Liechtenstein',
    name: 'Liechtenstein',
    ISO3: 'LIE',
    ISO: 'LR',
    independent: true,
    i18nKey: 'countries.liechtenstein',
  },
  FLK: {
    NAT: 'FLK',
    nameDE: 'Falklandinseln',
    name: 'Falkland Islands (Malvinas)',
    ISO3: 'FLK',
    ISO: 'FK',
    independent: false,
    i18nKey: 'countries.falklandinseln',
  },
  FRO: {
    NAT: 'FRO',
    nameDE: 'Färöer',
    name: 'Faroe Islands',
    ISO3: 'FRO',
    ISO: 'FO',
    independent: false,
    i18nKey: 'countries.faeroeer',
  },
  FJI: {
    NAT: 'FJI',
    nameDE: 'Fiji',
    name: 'Fiji',
    ISO3: 'FJI',
    ISO: 'FJ',
    independent: true,
    i18nKey: 'countries.fidschi',
  },
  FIN: {
    NAT: 'FIN',
    nameDE: 'Finnland',
    name: 'Finland',
    ISO3: 'FIN',
    ISO: 'FI',
    independent: true,
    i18nKey: 'countries.finnland',
  },
  FRA: {
    NAT: 'FRA',
    nameDE: 'Frankreich',
    name: 'France',
    ISO3: 'FRA',
    ISO: 'FR',
    independent: true,
    i18nKey: 'countries.frankreich',
  },
  ATF: {
    NAT: 'ATF',
    nameDE: 'Französische Süd- und Antarktisgebiete',
    name: 'French Southern Territories',
    ISO3: 'ATF',
    ISO: 'TF',
    independent: false,
    i18nKey: 'countries.franzoesische-sued-und-antarktisgebiete',
  },
  GUF: {
    NAT: 'GUF',
    nameDE: 'Französisch-Guayana',
    name: 'French Guiana',
    ISO3: 'GUF',
    ISO: 'GF',
    independent: false,
    i18nKey: 'countries.franzoesisch-guayana',
  },
  PYF: {
    NAT: 'PYF',
    nameDE: 'Französisch-Polynesien',
    name: 'French Polynesia',
    ISO3: 'PYF',
    ISO: 'PF',
    independent: false,
    i18nKey: 'countries.franzoesisch-polynesien',
  },
  GAB: {
    NAT: 'GAB',
    nameDE: 'Gabun',
    name: 'Gabon',
    ISO3: 'GAB',
    ISO: 'GA',
    independent: true,
    i18nKey: 'countries.gabun',
  },
  GMB: {
    NAT: 'GMB',
    nameDE: 'Gambia',
    name: 'Gambia',
    ISO3: 'GMB',
    ISO: 'GM',
    independent: true,
    i18nKey: 'countries.gambia',
  },
  GEO: {
    NAT: 'GEO',
    nameDE: 'Georgien',
    name: 'Georgia',
    ISO3: 'GEO',
    ISO: 'GE',
    independent: true,
    i18nKey: 'countries.georgien',
  },
  GHA: {
    NAT: 'GHA',
    nameDE: 'Ghana',
    name: 'Ghana',
    ISO3: 'GHA',
    ISO: 'GH',
    independent: true,
    i18nKey: 'countries.ghana',
  },
  GIB: {
    NAT: 'GIB',
    nameDE: 'Gibraltar',
    name: 'Gibraltar',
    ISO3: 'GIB',
    ISO: 'GI',
    independent: false,
    i18nKey: 'countries.gibraltar',
  },
  GRD: {
    NAT: 'GRD',
    nameDE: 'Grenada',
    name: 'Grenada',
    ISO3: 'GRD',
    ISO: 'GD',
    independent: true,
    i18nKey: 'countries.grenada',
  },
  GRC: {
    NAT: 'GRC',
    nameDE: 'Griechenland',
    name: 'Greece',
    ISO3: 'GRC',
    ISO: 'GR',
    independent: true,
    i18nKey: 'countries.griechenland',
  },
  GRL: {
    NAT: 'GRL',
    nameDE: 'Grönland',
    name: 'Greenland',
    ISO3: 'GRL',
    ISO: 'GL',
    independent: false,
    i18nKey: 'countries.groenland',
  },
  GBR: {
    NAT: 'GBR',
    nameDE: 'Großbritannien',
    name: 'United Kingdom',
    ISO3: 'GBR',
    ISO: 'GB',
    independent: true,
    i18nKey: 'countries.grossbritannien',
  },
  GLP: {
    NAT: 'GLP',
    nameDE: 'Guadeloupe',
    name: 'Guadeloupe',
    ISO3: 'GLP',
    ISO: 'GP',
    independent: false,
    i18nKey: 'countries.guadeloupe',
  },
  GUM: {
    NAT: 'GUM',
    nameDE: 'Guam',
    name: 'Guam',
    ISO3: 'GUM',
    ISO: 'GU',
    independent: false,
    i18nKey: 'countries.guam',
  },
  GTM: {
    NAT: 'GTM',
    nameDE: 'Guatemala',
    name: 'Guatemala',
    ISO3: 'GTM',
    ISO: 'GT',
    independent: true,
    i18nKey: 'countries.guatemala',
  },
  GGY: {
    NAT: 'GGY',
    nameDE: 'Guernsey (Kanalinsel)',
    name: 'Guernsey',
    ISO3: 'GGY',
    ISO: 'GG',
    independent: false,
    i18nKey: 'countries.guernsey',
  },
  GIN: {
    NAT: 'GIN',
    nameDE: 'Guinea',
    name: 'Guinea',
    ISO3: 'GIN',
    ISO: 'GN',
    independent: true,
    i18nKey: 'countries.guinea',
  },
  GNB: {
    NAT: 'GNB',
    nameDE: 'Guinea-Bissau',
    name: 'Guinea-Bissau',
    ISO3: 'GNB',
    ISO: 'GW',
    independent: true,
    i18nKey: 'countries.guinea-bissau',
  },
  GUY: {
    NAT: 'GUY',
    nameDE: 'Guyana',
    name: 'Guyana',
    ISO3: 'GUY',
    ISO: 'GY',
    independent: true,
    i18nKey: 'countries.guyana',
  },
  HTI: {
    NAT: 'HTI',
    nameDE: 'Haiti',
    name: 'Haiti',
    ISO3: 'HTI',
    ISO: 'HT',
    independent: true,
    i18nKey: 'countries.haiti',
  },
  HMD: {
    NAT: 'HMD',
    nameDE: 'Heard und McDonaldinseln',
    name: 'Heard Island and McDonald Islands',
    ISO3: 'HMD',
    ISO: 'HM',
    independent: false,
    i18nKey: 'countries.heard-und-mcdonaldinseln',
  },
  HND: {
    NAT: 'HND',
    nameDE: 'Honduras',
    name: 'Honduras',
    ISO3: 'HND',
    ISO: 'HN',
    independent: true,
    i18nKey: 'countries.honduras',
  },
  HKG: {
    NAT: 'HKG',
    nameDE: 'Hong Kong',
    name: 'Hong Kong',
    ISO3: 'HKG',
    ISO: 'HK',
    independent: false,
    i18nKey: 'countries.hong-kong-s-a-r-china',
  },
  IND: {
    NAT: 'IND',
    nameDE: 'Indien',
    name: 'India',
    ISO3: 'IND',
    ISO: 'IN',
    independent: true,
    i18nKey: 'countries.indien',
  },
  IDN: {
    NAT: 'IDN',
    nameDE: 'Indonesien',
    name: 'Indonesia',
    ISO3: 'IDN',
    ISO: 'ID',
    independent: true,
    i18nKey: 'countries.indonesien',
  },
  IRQ: {
    NAT: 'IRQ',
    nameDE: 'Irak',
    name: 'Iraq',
    ISO3: 'IRQ',
    ISO: 'IQ',
    independent: true,
    i18nKey: 'countries.irak',
  },
  IRN: {
    NAT: 'IRN',
    nameDE: 'Iran',
    name: 'Iran',
    ISO3: 'IRN',
    ISO: 'IR',
    independent: true,
    i18nKey: 'countries.iran',
  },
  IRL: {
    NAT: 'IRL',
    nameDE: 'Irland',
    name: 'Ireland',
    ISO3: 'IRL',
    ISO: 'IE',
    independent: true,
    i18nKey: 'countries.irland',
  },
  ISL: {
    NAT: 'ISL',
    nameDE: 'Island',
    name: 'Iceland',
    ISO3: 'ISL',
    ISO: 'IS',
    independent: true,
    i18nKey: 'countries.island',
  },
  IMN: {
    NAT: 'IMN',
    nameDE: 'Isle of Man',
    name: 'Isle of Man',
    ISO3: 'IMN',
    ISO: 'IM',
    independent: false,
    i18nKey: 'countries.insel-man',
  },
  ISR: {
    NAT: 'ISR',
    nameDE: 'Israel',
    name: 'Israel',
    ISO3: 'ISR',
    ISO: 'IL',
    independent: true,
    i18nKey: 'countries.israel',
  },
  ITA: {
    NAT: 'ITA',
    nameDE: 'Italien',
    name: 'Italy',
    ISO3: 'ITA',
    ISO: 'IT',
    independent: true,
    i18nKey: 'countries.italien',
  },
  JAM: {
    NAT: 'JAM',
    nameDE: 'Jamaika',
    name: 'Jamaica',
    ISO3: 'JAM',
    ISO: 'JM',
    independent: true,
    i18nKey: 'countries.jamaika',
  },
  JPN: {
    NAT: 'JPN',
    nameDE: 'Japan',
    name: 'Japan',
    ISO3: 'JPN',
    ISO: 'JP',
    independent: true,
    i18nKey: 'countries.japan',
  },
  YEM: {
    NAT: 'YEM',
    nameDE: 'Jemen',
    name: 'Yemen',
    ISO3: 'YEM',
    ISO: 'YE',
    independent: true,
    i18nKey: 'countries.jemen',
  },
  JEY: {
    NAT: 'JEY',
    nameDE: 'Jersey (Kanalinsel)',
    name: 'Jersey',
    ISO3: 'JEY',
    ISO: 'JE',
    independent: false,
    i18nKey: 'countries.jersey',
  },
  JOR: {
    NAT: 'JOR',
    nameDE: 'Jordanien',
    name: 'Jordan',
    ISO3: 'JOR',
    ISO: 'JO',
    independent: true,
    i18nKey: 'countries.jordanien',
  },
  KHM: {
    NAT: 'KHM',
    nameDE: 'Kambodscha',
    name: 'Cambodia',
    ISO3: 'KHM',
    ISO: 'KH',
    independent: true,
    i18nKey: 'countries.kambodscha',
  },
  CMR: {
    NAT: 'CMR',
    nameDE: 'Kamerun',
    name: 'Cameroon',
    ISO3: 'CMR',
    ISO: 'CM',
    independent: true,
    i18nKey: 'countries.kamerun',
  },
  CAN: {
    NAT: 'CAN',
    nameDE: 'Kanada',
    name: 'Canada',
    ISO3: 'CAN',
    ISO: 'CA',
    independent: true,
    i18nKey: 'countries.kanada',
  },
  CPV: {
    NAT: 'CPV',
    nameDE: 'Kap Verde',
    name: 'Cabo Verde',
    ISO3: 'CPV',
    ISO: 'CV',
    independent: true,
    i18nKey: 'countries.kap-verde',
  },
  KAZ: {
    NAT: 'KAZ',
    nameDE: 'Kasachstan',
    name: 'Kazakhstan',
    ISO3: 'KAZ',
    ISO: 'KZ',
    independent: true,
    i18nKey: 'countries.kasachstan',
  },
  QAT: {
    NAT: 'QAT',
    nameDE: 'Katar',
    name: 'Qatar',
    ISO3: 'QAT',
    ISO: 'PT',
    independent: true,
    i18nKey: 'countries.katar',
  },
  KEN: {
    NAT: 'KEN',
    nameDE: 'Kenia',
    name: 'Kenya',
    ISO3: 'KEN',
    ISO: 'KE',
    independent: true,
    i18nKey: 'countries.kenia',
  },
  KGZ: {
    NAT: 'KGZ',
    nameDE: 'Kirgisistan',
    name: 'Kyrgyzstan',
    ISO3: 'KGZ',
    ISO: 'KR',
    independent: true,
    i18nKey: 'countries.kirgisistan',
  },
  KIR: {
    NAT: 'KIR',
    nameDE: 'Kiribati',
    name: 'Kiribati',
    ISO3: 'KIR',
    ISO: 'KI',
    independent: true,
    i18nKey: 'countries.kiribati',
  },
  CCK: {
    NAT: 'CCK',
    nameDE: 'Kokosinseln',
    name: 'Cocos (Keeling) Islands',
    ISO3: 'CCK',
    ISO: 'CC',
    independent: false,
    i18nKey: 'countries.kokosinseln-keeling',
  },
  COL: {
    NAT: 'COL',
    nameDE: 'Kolumbien',
    name: 'Colombia',
    ISO3: 'COL',
    ISO: 'CO',
    independent: true,
    i18nKey: 'countries.kolumbien',
  },
  COM: {
    NAT: 'COM',
    nameDE: 'Komoren',
    name: 'Comoros',
    ISO3: 'COM',
    ISO: 'KM',
    independent: true,
    i18nKey: 'countries.komoren',
  },
  XK: {
    NAT: 'XK',
    nameDE: 'Kosovo',
    name: 'Kosovo',
    ISO3: 'XK',
    ISO: 'XK',
    independent: true,
    i18nKey: 'countries.kosovo',
  },
  HRV: {
    NAT: 'HRV',
    nameDE: 'Kroatien',
    name: 'Croatia',
    ISO3: 'HRV',
    ISO: 'HR',
    independent: true,
    i18nKey: 'countries.kroatien',
  },
  CUB: {
    NAT: 'CUB',
    nameDE: 'Kuba',
    name: 'Cuba',
    ISO3: 'CUB',
    ISO: 'CU',
    independent: true,
    i18nKey: 'countries.kuba',
  },
  KWT: {
    NAT: 'KWT',
    nameDE: 'Kuwait',
    name: 'Kuwait',
    ISO3: 'KWT',
    ISO: 'KP',
    independent: true,
    i18nKey: 'countries.kuwait',
  },
  LAO: {
    NAT: 'LAO',
    nameDE: 'Laos',
    name: 'Laos',
    ISO3: 'LAO',
    ISO: 'KW',
    independent: true,
    i18nKey: 'countries.laos',
  },
  LSO: {
    NAT: 'LSO',
    nameDE: 'Lesotho',
    name: 'Lesotho',
    ISO3: 'LSO',
    ISO: 'LV',
    independent: true,
    i18nKey: 'countries.lesotho',
  },
  LVA: {
    NAT: 'LVA',
    nameDE: 'Lettland',
    name: 'Latvia',
    ISO3: 'LVA',
    ISO: 'KG',
    independent: true,
    i18nKey: 'countries.lettland',
  },
  LBN: {
    NAT: 'LBN',
    nameDE: 'Libanon',
    name: 'Lebanon',
    ISO3: 'LBN',
    ISO: 'LA',
    independent: true,
    i18nKey: 'countries.libanon',
  },
  LBR: {
    NAT: 'LBR',
    nameDE: 'Liberien',
    name: 'Liberia',
    ISO3: 'LBR',
    ISO: 'LB',
    independent: true,
    i18nKey: 'countries.liberia',
  },
  LTU: {
    NAT: 'LTU',
    nameDE: 'Litauen',
    name: 'Lithuania',
    ISO3: 'LTU',
    ISO: 'LY',
    independent: true,
    i18nKey: 'countries.litauen',
  },
  LUX: {
    NAT: 'LUX',
    nameDE: 'Luxemburg',
    name: 'Luxembourg',
    ISO3: 'LUX',
    ISO: 'LI',
    independent: true,
    i18nKey: 'countries.luxemburg',
  },
  LBY: {
    NAT: 'LBY',
    nameDE: 'Lybien',
    name: 'Libya',
    ISO3: 'LBY',
    ISO: 'LS',
    independent: true,
    i18nKey: 'countries.libyen',
  },
  MAC: {
    NAT: 'MAC',
    nameDE: 'Macau',
    name: 'Macao',
    ISO3: 'MAC',
    ISO: 'MO',
    independent: false,
    i18nKey: 'countries.macau-s-a-r-china',
  },
  MDG: {
    NAT: 'MDG',
    nameDE: 'Madagakar',
    name: 'Madagascar',
    ISO3: 'MDG',
    ISO: 'LT',
    independent: true,
    i18nKey: 'countries.madagaskar',
  },
  MWI: {
    NAT: 'MWI',
    nameDE: 'Malawi',
    name: 'Malawi',
    ISO3: 'MWI',
    ISO: 'LU',
    independent: true,
    i18nKey: 'countries.malawi',
  },
  MYS: {
    NAT: 'MYS',
    nameDE: 'Malaysia',
    name: 'Malaysia',
    ISO3: 'MYS',
    ISO: 'MG',
    independent: true,
    i18nKey: 'countries.malaysia',
  },
  MDV: {
    NAT: 'MDV',
    nameDE: 'Malediven',
    name: 'Maldives',
    ISO3: 'MDV',
    ISO: 'MW',
    independent: true,
    i18nKey: 'countries.malediven',
  },
  MLI: {
    NAT: 'MLI',
    nameDE: 'Mali',
    name: 'Mali',
    ISO3: 'MLI',
    ISO: 'MY',
    independent: true,
    i18nKey: 'countries.mali',
  },
  MLT: {
    NAT: 'MLT',
    nameDE: 'Malta',
    name: 'Malta',
    ISO3: 'MLT',
    ISO: 'MV',
    independent: true,
    i18nKey: 'countries.malta',
  },
  MAR: {
    NAT: 'MAR',
    nameDE: 'Marokko',
    name: 'Morocco',
    ISO3: 'MAR',
    ISO: 'MN',
    independent: true,
    i18nKey: 'countries.marokko',
  },
  MHL: {
    NAT: 'MHL',
    nameDE: 'Marshallinseln',
    name: 'Marshall Islands',
    ISO3: 'MHL',
    ISO: 'ML',
    independent: true,
    i18nKey: 'countries.marschallinseln',
  },
  MTQ: {
    NAT: 'MTQ',
    nameDE: 'Martinique',
    name: 'Martinique',
    ISO3: 'MTQ',
    ISO: 'MQ',
    independent: false,
    i18nKey: 'countries.martinique',
  },
  MRT: {
    NAT: 'MRT',
    nameDE: 'Mauretanien',
    name: 'Mauritania',
    ISO3: 'MRT',
    ISO: 'MT',
    independent: true,
    i18nKey: 'countries.mauretanien',
  },
  MUS: {
    NAT: 'MUS',
    nameDE: 'Mauritius',
    name: 'Mauritius',
    ISO3: 'MUS',
    ISO: 'MH',
    independent: true,
    i18nKey: 'countries.mauritius',
  },
  MYT: {
    NAT: 'MYT',
    nameDE: 'Mayotte',
    name: 'Mayotte',
    ISO3: 'MYT',
    ISO: 'YT',
    independent: false,
    i18nKey: 'countries.mayotte',
  },
  MKD: {
    NAT: 'MKD',
    nameDE: 'Mazedonien',
    name: 'North Macedonia',
    ISO3: 'MKD',
    ISO: 'NG',
    independent: true,
    i18nKey: 'countries.mazedonien',
  },
  MEX: {
    NAT: 'MEX',
    nameDE: 'Mexiko',
    name: 'Mexico',
    ISO3: 'MEX',
    ISO: 'MR',
    independent: true,
    i18nKey: 'countries.mexiko',
  },
  FSM: {
    NAT: 'FSM',
    nameDE: 'Mikronesien',
    name: 'Micronesia',
    ISO3: 'FSM',
    ISO: 'MU',
    independent: true,
    i18nKey: 'countries.mikronesien',
  },
  MDA: {
    NAT: 'MDA',
    nameDE: 'Moldawien',
    name: 'Moldova',
    ISO3: 'MDA',
    ISO: 'MX',
    independent: true,
    i18nKey: 'countries.moldawien-republik-moldau',
  },
  MCO: {
    NAT: 'MCO',
    nameDE: 'Monaco',
    name: 'Monaco',
    ISO3: 'MCO',
    ISO: 'FM',
    independent: true,
    i18nKey: 'countries.monaco',
  },
  MNG: {
    NAT: 'MNG',
    nameDE: 'Mongolei',
    name: 'Mongolia',
    ISO3: 'MNG',
    ISO: 'MD',
    independent: true,
    i18nKey: 'countries.mongolei',
  },
  MNE: {
    NAT: 'MNE',
    nameDE: 'Montenegro',
    name: 'Montenegro',
    ISO3: 'MNE',
    ISO: 'MC',
    independent: true,
    i18nKey: 'countries.montenegro',
  },
  MSR: {
    NAT: 'MSR',
    nameDE: 'Montserrat',
    name: 'Montserrat',
    ISO3: 'MSR',
    ISO: 'MS',
    independent: false,
    i18nKey: 'countries.montserrat',
  },
  MOZ: {
    NAT: 'MOZ',
    nameDE: 'Mosambik',
    name: 'Mozambique',
    ISO3: 'MOZ',
    ISO: 'ME',
    independent: true,
    i18nKey: 'countries.mosambik',
  },
  MMR: {
    NAT: 'MMR',
    nameDE: 'Myanmar (Burma)',
    name: 'Myanmar',
    ISO3: 'MMR',
    ISO: 'MA',
    independent: true,
    i18nKey: 'countries.myanmar',
  },
  NAM: {
    NAT: 'NAM',
    nameDE: 'Namibia',
    name: 'Namibia',
    ISO3: 'NAM',
    ISO: 'MZ',
    independent: true,
    i18nKey: 'countries.namibia',
  },
  NRU: {
    NAT: 'NRU',
    nameDE: 'Nauru',
    name: 'Nauru',
    ISO3: 'NRU',
    ISO: 'MM',
    independent: true,
    i18nKey: 'countries.nauru',
  },
  NPL: {
    NAT: 'NPL',
    nameDE: 'Nepal',
    name: 'Nepal',
    ISO3: 'NPL',
    ISO: 'NA',
    independent: true,
    i18nKey: 'countries.nepal',
  },
  NCL: {
    NAT: 'NCL',
    nameDE: 'Neukaledonien',
    name: 'New Caledonia',
    ISO3: 'NCL',
    ISO: 'NC',
    independent: false,
    i18nKey: 'countries.neukaledonien',
  },
  NZL: {
    NAT: 'NZL',
    nameDE: 'Neuseeland',
    name: 'New Zealand',
    ISO3: 'NZL',
    ISO: 'NP',
    independent: true,
    i18nKey: 'countries.neuseeland',
  },
  NIC: {
    NAT: 'NIC',
    nameDE: 'Nicaragua',
    name: 'Nicaragua',
    ISO3: 'NIC',
    ISO: 'NL',
    independent: true,
    i18nKey: 'countries.nicaragua',
  },
  NLD: {
    NAT: 'NLD',
    nameDE: 'Niederlande',
    name: 'Netherlands',
    ISO3: 'NLD',
    ISO: 'NR',
    independent: true,
    i18nKey: 'countries.niederlande',
  },
  NER: {
    NAT: 'NER',
    nameDE: 'Niger',
    name: 'Niger',
    ISO3: 'NER',
    ISO: 'NZ',
    independent: true,
    i18nKey: 'countries.niger',
  },
  NGA: {
    NAT: 'NGA',
    nameDE: 'Nigeria',
    name: 'Nigeria',
    ISO3: 'NGA',
    ISO: 'NI',
    independent: true,
    i18nKey: 'countries.nigeria',
  },
  NIU: {
    NAT: 'NIU',
    nameDE: 'Niue',
    name: 'Niue',
    ISO3: 'NIU',
    ISO: 'NU',
    independent: false,
    i18nKey: 'countries.niue',
  },
  PRK: {
    NAT: 'PRK',
    nameDE: 'Nordkorea',
    name: "Korea (Democratic People's Republic Of)",
    ISO3: 'PRK',
    ISO: 'NE',
    independent: true,
    i18nKey: 'countries.demokratische-volksrepublik-korea',
  },
  MNP: {
    NAT: 'MNP',
    nameDE: 'Nördliche Marianen',
    name: 'Northern Mariana Islands',
    ISO3: 'MNP',
    ISO: 'MP',
    independent: false,
    i18nKey: 'countries.noerdliche-marianen',
  },
  NFK: {
    NAT: 'NFK',
    nameDE: 'Norfolkinsel',
    name: 'Norfolk Island',
    ISO3: 'NFK',
    ISO: 'NF',
    independent: false,
    i18nKey: 'countries.norfolkinsel',
  },
  NOR: {
    NAT: 'NOR',
    nameDE: 'Norwegen',
    name: 'Norway',
    ISO3: 'NOR',
    ISO: 'MK',
    independent: true,
    i18nKey: 'countries.norwegen',
  },
  OMN: {
    NAT: 'OMN',
    nameDE: 'Oman',
    name: 'Oman',
    ISO3: 'OMN',
    ISO: 'NO',
    independent: true,
    i18nKey: 'countries.oman',
  },
  AUT: {
    NAT: 'AUT',
    nameDE: 'Österreich',
    name: 'Austria',
    ISO3: 'AUT',
    ISO: 'AT',
    independent: true,
    i18nKey: 'countries.oesterreich',
  },
  TLS: {
    NAT: 'TLS',
    nameDE: 'Osttimor (Timor-Leste)',
    name: 'Timor-Leste',
    ISO3: 'TLS',
    ISO: 'TL',
    independent: true,
    i18nKey: 'countries.osttimor',
  },
  PAK: {
    NAT: 'PAK',
    nameDE: 'Pakistan',
    name: 'Pakistan',
    ISO3: 'PAK',
    ISO: 'OM',
    independent: true,
    i18nKey: 'countries.pakistan',
  },
  PSE: {
    NAT: 'PSE',
    nameDE: 'Palästina',
    name: 'Palestine',
    ISO3: 'PSE',
    ISO: 'PS',
    independent: false,
    i18nKey: 'countries.palaestina',
  },
  PLW: {
    NAT: 'PLW',
    nameDE: 'Palau',
    name: 'Palau',
    ISO3: 'PLW',
    ISO: 'PK',
    independent: true,
    i18nKey: 'countries.palau',
  },
  PAN: {
    NAT: 'PAN',
    nameDE: 'Panama',
    name: 'Panama',
    ISO3: 'PAN',
    ISO: 'PW',
    independent: true,
    i18nKey: 'countries.panama',
  },
  PNG: {
    NAT: 'PNG',
    nameDE: 'Papua-Neuguinea',
    name: 'Papua New Guinea',
    ISO3: 'PNG',
    ISO: 'PA',
    independent: true,
    i18nKey: 'countries.papua-neuguinea',
  },
  PRY: {
    NAT: 'PRY',
    nameDE: 'Paraguay',
    name: 'Paraguay',
    ISO3: 'PRY',
    ISO: 'PG',
    independent: true,
    i18nKey: 'countries.paraguay',
  },
  PER: {
    NAT: 'PER',
    nameDE: 'Peru',
    name: 'Peru',
    ISO3: 'PER',
    ISO: 'PY',
    independent: true,
    i18nKey: 'countries.peru',
  },
  PHL: {
    NAT: 'PHL',
    nameDE: 'Philippinen',
    name: 'Philippines',
    ISO3: 'PHL',
    ISO: 'PE',
    independent: true,
    i18nKey: 'countries.philippinen',
  },
  PCN: {
    NAT: 'PCN',
    nameDE: 'Pitcairninseln',
    name: 'Pitcairn',
    ISO3: 'PCN',
    ISO: 'PN',
    independent: false,
    i18nKey: 'countries.pitcairn',
  },
  POL: {
    NAT: 'POL',
    nameDE: 'Polen',
    name: 'Poland',
    ISO3: 'POL',
    ISO: 'PH',
    independent: true,
    i18nKey: 'countries.polen',
  },
  PRT: {
    NAT: 'PRT',
    nameDE: 'Portugal',
    name: 'Portugal',
    ISO3: 'PRT',
    ISO: 'PL',
    independent: true,
    i18nKey: 'countries.portugal',
  },
  PRI: {
    NAT: 'PRI',
    nameDE: 'Puerto Rico',
    name: 'Puerto Rico',
    ISO3: 'PRI',
    ISO: 'PR',
    independent: false,
    i18nKey: 'countries.puerto-rico',
  },
  COG: {
    NAT: 'COG',
    nameDE: 'Republik Kongo',
    name: 'Congo',
    ISO3: 'COG',
    ISO: 'CG',
    independent: true,
    i18nKey: 'countries.kongo',
  },
  REU: {
    NAT: 'REU',
    nameDE: 'Réunion',
    name: 'Réunion',
    ISO3: 'REU',
    ISO: 'RE',
    independent: false,
    i18nKey: 'countries.reunion',
  },
  RWA: {
    NAT: 'RWA',
    nameDE: 'Ruanda',
    name: 'Rwanda',
    ISO3: 'RWA',
    ISO: 'RU',
    independent: true,
    i18nKey: 'countries.ruanda',
  },
  ROU: {
    NAT: 'ROU',
    nameDE: 'Rumänien',
    name: 'Romania',
    ISO3: 'ROU',
    ISO: 'QA',
    independent: true,
    i18nKey: 'countries.rumaenien',
  },
  RUS: {
    NAT: 'RUS',
    nameDE: 'Russland',
    name: 'Russian Federation',
    ISO3: 'RUS',
    ISO: 'RO',
    independent: true,
    i18nKey: 'countries.russische-foederation',
  },
  LCA: {
    NAT: 'LCA',
    nameDE: 'Saint Lucia',
    name: 'Saint Lucia',
    ISO3: 'LCA',
    ISO: 'KN',
    independent: true,
    i18nKey: 'countries.st-lucia',
  },
  BLM: {
    NAT: 'BLM',
    nameDE: 'Saint-Barthélemy',
    name: 'Saint Barthélemy',
    ISO3: 'BLM',
    ISO: 'BL',
    independent: false,
    i18nKey: 'countries.saint-barthelemy',
  },
  MAF: {
    NAT: 'MAF',
    nameDE: 'Saint-Martin (französischer Teil)',
    name: 'Saint Martin (French part)',
    ISO3: 'MAF',
    ISO: 'MF',
    independent: false,
    i18nKey: 'countries.saint-martin',
  },
  SPM: {
    NAT: 'SPM',
    nameDE: 'Saint-Pierre und Miquelon',
    name: 'Saint Pierre and Miquelon',
    ISO3: 'SPM',
    ISO: 'PM',
    independent: false,
    i18nKey: 'countries.st-pierre-und-miquelon',
  },
  SLB: {
    NAT: 'SLB',
    nameDE: 'Salomonen',
    name: 'Solomon Islands',
    ISO3: 'SLB',
    ISO: 'SI',
    independent: true,
    i18nKey: 'countries.salomonen',
  },
  ZMB: {
    NAT: 'ZMB',
    nameDE: 'Sambia',
    name: 'Zambia',
    ISO3: 'ZMB',
    ISO: 'ZM',
    independent: true,
    i18nKey: 'countries.sambia',
  },
  WSM: {
    NAT: 'WSM',
    nameDE: 'Samoa',
    name: 'Samoa',
    ISO3: 'WSM',
    ISO: 'VC',
    independent: true,
    i18nKey: 'countries.samoa',
  },
  SMR: {
    NAT: 'SMR',
    nameDE: 'San Marino',
    name: 'San Marino',
    ISO3: 'SMR',
    ISO: 'WS',
    independent: true,
    i18nKey: 'countries.san-marino',
  },
  STP: {
    NAT: 'STP',
    nameDE: 'São Tomé und Príncipe',
    name: 'Sao Tome and Principe',
    ISO3: 'STP',
    ISO: 'SM',
    independent: true,
    i18nKey: 'countries.sao-tome-und-principe',
  },
  SAU: {
    NAT: 'SAU',
    nameDE: 'Saudi Arabien',
    name: 'Saudi Arabia',
    ISO3: 'SAU',
    ISO: 'ST',
    independent: true,
    i18nKey: 'countries.saudi-arabien',
  },
  SWE: {
    NAT: 'SWE',
    nameDE: 'Schweden',
    name: 'Sweden',
    ISO3: 'SWE',
    ISO: 'SE',
    independent: true,
    i18nKey: 'countries.schweden',
  },
  CHE: {
    NAT: 'CHE',
    nameDE: 'Schweiz',
    name: 'Switzerland',
    ISO3: 'CHE',
    ISO: 'CH',
    independent: true,
    i18nKey: 'countries.schweiz',
  },
  SEN: {
    NAT: 'SEN',
    nameDE: 'Senegal',
    name: 'Senegal',
    ISO3: 'SEN',
    ISO: 'SA',
    independent: true,
    i18nKey: 'countries.senegal',
  },
  SRB: {
    NAT: 'SRB',
    nameDE: 'Serbien',
    name: 'Serbia',
    ISO3: 'SRB',
    ISO: 'SN',
    independent: true,
    i18nKey: 'countries.serbien',
  },
  SYC: {
    NAT: 'SYC',
    nameDE: 'Seychellen',
    name: 'Seychelles',
    ISO3: 'SYC',
    ISO: 'RS',
    independent: true,
    i18nKey: 'countries.seychellen',
  },
  SLE: {
    NAT: 'SLE',
    nameDE: 'Sierra Leone',
    name: 'Sierra Leone',
    ISO3: 'SLE',
    ISO: 'SC',
    independent: true,
    i18nKey: 'countries.sierra-leone',
  },
  ZWE: {
    NAT: 'ZWE',
    nameDE: 'Simbabwe',
    name: 'Zimbabwe',
    ISO3: 'ZWE',
    ISO: 'ZW',
    independent: true,
    i18nKey: 'countries.simbabwe',
  },
  SGP: {
    NAT: 'SGP',
    nameDE: 'Singapur',
    name: 'Singapore',
    ISO3: 'SGP',
    ISO: 'SL',
    independent: true,
    i18nKey: 'countries.singapur',
  },
  SXM: {
    NAT: 'SXM',
    nameDE: 'Sint Maarten',
    name: 'Sint Maarten (Dutch part)',
    ISO3: 'SXM',
    ISO: 'SX',
    independent: false,
    i18nKey: 'countries.sint-maarten',
  },
  SVK: {
    NAT: 'SVK',
    nameDE: 'Slowakei',
    name: 'Slovakia',
    ISO3: 'SVK',
    ISO: 'SG',
    independent: true,
    i18nKey: 'countries.slowakei',
  },
  SVN: {
    NAT: 'SVN',
    nameDE: 'Slowenien',
    name: 'Slovenia',
    ISO3: 'SVN',
    ISO: 'SK',
    independent: true,
    i18nKey: 'countries.slowenien',
  },
  SOM: {
    NAT: 'SOM',
    nameDE: 'Somalia',
    name: 'Somalia',
    ISO3: 'SOM',
    ISO: 'SB',
    independent: true,
    i18nKey: 'countries.somalia',
  },
  ESP: {
    NAT: 'ESP',
    nameDE: 'Spanien',
    name: 'Spain',
    ISO3: 'ESP',
    ISO: 'ES',
    independent: true,
    i18nKey: 'countries.spanien',
  },
  SJM: {
    NAT: 'SJM',
    nameDE: 'Spitzbergen und Jan Mayen',
    name: 'Svalbard and Jan Mayen',
    ISO3: 'SJM',
    ISO: 'SJ',
    independent: false,
    i18nKey: 'countries.svalbard-und-jan-mayen',
  },
  LKA: {
    NAT: 'LKA',
    nameDE: 'Sri Lanka',
    name: 'Sri Lanka',
    ISO3: 'LKA',
    ISO: 'LK',
    independent: true,
    i18nKey: 'countries.sri-lanka',
  },
  SHN: {
    NAT: 'SHN',
    nameDE: 'St. Helena, Ascension und Tristan da Cunha',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    ISO3: 'SHN',
    ISO: 'SH',
    independent: false,
    i18nKey: 'countries.st-helena',
  },
  KNA: {
    NAT: 'KNA',
    nameDE: 'St. Kitts und Nevis',
    name: 'Saint Kitts and Nevis',
    ISO3: 'KNA',
    ISO: 'RW',
    independent: true,
    i18nKey: 'countries.st-kitts-und-nevis',
  },
  VCT: {
    NAT: 'VCT',
    nameDE: 'St. Vincent und die Grenadinen',
    name: 'Saint Vincent and the Grenadines',
    ISO3: 'VCT',
    ISO: 'LC',
    independent: true,
    i18nKey: 'countries.st-vinzent-und-die-grenadinen',
  },
  ZAF: {
    NAT: 'ZAF',
    nameDE: 'Südafrika',
    name: 'South Africa',
    ISO3: 'ZAF',
    ISO: 'SO',
    independent: true,
    i18nKey: 'countries.suedafrika',
  },
  SDN: {
    NAT: 'SDN',
    nameDE: 'Sudan',
    name: 'Sudan',
    ISO3: 'SDN',
    ISO: 'SD',
    independent: true,
    i18nKey: 'countries.sudan',
  },
  SGS: {
    NAT: 'SGS',
    nameDE: 'Südgeorgien und die Südlichen Sandwichinseln',
    name: 'South Georgia and the South Sandwich Islands',
    ISO3: 'SGS',
    ISO: 'GS',
    independent: false,
    i18nKey: 'countries.suedgeorgien-und-die-suedlichen-sandwichinseln',
  },
  KOR: {
    NAT: 'KOR',
    nameDE: 'Südkorea',
    name: 'Korea (Republic of)',
    ISO3: 'KOR',
    ISO: 'ZA',
    independent: true,
    i18nKey: 'countries.republik-korea',
  },
  SSD: {
    NAT: 'SSD',
    nameDE: 'Südsudan',
    name: 'South Sudan',
    ISO3: 'SSD',
    ISO: 'SS',
    independent: true,
    i18nKey: 'countries.suedsudan',
  },
  SUR: {
    NAT: 'SUR',
    nameDE: 'Surinam',
    name: 'Suriname',
    ISO3: 'SUR',
    ISO: 'SR',
    independent: true,
    i18nKey: 'countries.suriname',
  },
  SYR: {
    NAT: 'SYR',
    nameDE: 'Syrien',
    name: 'Syria',
    ISO3: 'SYR',
    ISO: 'SY',
    independent: true,
    i18nKey: 'countries.syrien',
  },
  TJK: {
    NAT: 'TJK',
    nameDE: 'Tadschikistan',
    name: 'Tajikistan',
    ISO3: 'TJK',
    ISO: 'TJ',
    independent: true,
    i18nKey: 'countries.tadschikistan',
  },
  TWN: {
    NAT: 'TWN',
    nameDE: 'Taiwan',
    name: 'Taiwan',
    ISO3: 'TWN',
    ISO: 'TW',
    independent: false,
    i18nKey: 'countries.taiwan',
  },
  TZA: {
    NAT: 'TZA',
    nameDE: 'Tansania',
    name: 'Tanzania',
    ISO3: 'TZA',
    ISO: 'TZ',
    independent: true,
    i18nKey: 'countries.tansania',
  },
  THA: {
    NAT: 'THA',
    nameDE: 'Thailand',
    name: 'Thailand',
    ISO3: 'THA',
    ISO: 'TH',
    independent: true,
    i18nKey: 'countries.thailand',
  },
  TGO: {
    NAT: 'TGO',
    nameDE: 'Togo',
    name: 'Togo',
    ISO3: 'TGO',
    ISO: 'TG',
    independent: true,
    i18nKey: 'countries.togo',
  },
  TKL: {
    NAT: 'TKL',
    nameDE: 'Tokelau',
    name: 'Tokelau',
    ISO3: 'TKL',
    ISO: 'TK',
    independent: false,
    i18nKey: 'countries.tokelau',
  },
  TON: {
    NAT: 'TON',
    nameDE: 'Tonga',
    name: 'Tonga',
    ISO3: 'TON',
    ISO: 'TO',
    independent: true,
    i18nKey: 'countries.tonga',
  },
  TTO: {
    NAT: 'TTO',
    nameDE: 'Trinidad und Tobago',
    name: 'Trinidad and Tobago',
    ISO3: 'TTO',
    ISO: 'TT',
    independent: true,
    i18nKey: 'countries.trinidad-und-tobago',
  },
  TCD: {
    NAT: 'TCD',
    nameDE: 'Tschad',
    name: 'Chad',
    ISO3: 'TCD',
    ISO: 'TD',
    independent: true,
    i18nKey: 'countries.tschad',
  },
  CZE: {
    NAT: 'CZE',
    nameDE: 'Tschechische Republik',
    name: 'Czechia',
    ISO3: 'CZE',
    ISO: 'CZ',
    independent: true,
    i18nKey: 'countries.tschechische-republik',
  },
  TUN: {
    NAT: 'TUN',
    nameDE: 'Tunesien',
    name: 'Tunisia',
    ISO3: 'TUN',
    ISO: 'TN',
    independent: true,
    i18nKey: 'countries.tunesien',
  },
  TUR: {
    NAT: 'TUR',
    nameDE: 'Türkei',
    name: 'Turkey',
    ISO3: 'TUR',
    ISO: 'TR',
    independent: true,
    i18nKey: 'countries.tuerkei',
  },
  TKM: {
    NAT: 'TKM',
    nameDE: 'Turkmenistan',
    name: 'Turkmenistan',
    ISO3: 'TKM',
    ISO: 'TM',
    independent: true,
    i18nKey: 'countries.turkmenistan',
  },
  TCA: {
    NAT: 'TCA',
    nameDE: 'Turks- und Caicosinseln',
    name: 'Turks and Caicos Islands',
    ISO3: 'TCA',
    ISO: 'TC',
    independent: false,
    i18nKey: 'countries.turks-und-caicosinseln',
  },
  TUV: {
    NAT: 'TUV',
    nameDE: 'Tuvalu',
    name: 'Tuvalu',
    ISO3: 'TUV',
    ISO: 'TV',
    independent: true,
    i18nKey: 'countries.tuvalu',
  },
  UGA: {
    NAT: 'UGA',
    nameDE: 'Uganda',
    name: 'Uganda',
    ISO3: 'UGA',
    ISO: 'UG',
    independent: true,
    i18nKey: 'countries.uganda',
  },
  UKR: {
    NAT: 'UKR',
    nameDE: 'Ukraine',
    name: 'Ukraine',
    ISO3: 'UKR',
    ISO: 'UA',
    independent: true,
    i18nKey: 'countries.ukraine',
  },
  HUN: {
    NAT: 'HUN',
    nameDE: 'Ungarn',
    name: 'Hungary',
    ISO3: 'HUN',
    ISO: 'HU',
    independent: true,
    i18nKey: 'countries.ungarn',
  },
  UMI: {
    NAT: 'UMI',
    nameDE: 'United States Minor Outlying Islands',
    name: 'United States Minor Outlying Islands',
    ISO3: 'UMI',
    ISO: 'UM',
    independent: false,
    i18nKey: 'countries.amerikanisch-ozeanien',
  },
  URY: {
    NAT: 'URY',
    nameDE: 'Uruguay',
    name: 'Uruguay',
    ISO3: 'URY',
    ISO: 'UY',
    independent: true,
    i18nKey: 'countries.uruguay',
  },
  UZB: {
    NAT: 'UZB',
    nameDE: 'Usbekistan',
    name: 'Uzbekistan',
    ISO3: 'UZB',
    ISO: 'UZ',
    independent: true,
    i18nKey: 'countries.usbekistan',
  },
  VUT: {
    NAT: 'VUT',
    nameDE: 'Vanuatu',
    name: 'Vanuatu',
    ISO3: 'VUT',
    ISO: 'VU',
    independent: true,
    i18nKey: 'countries.vanuatu',
  },
  VAT: {
    NAT: 'VAT',
    nameDE: 'Vatikanstadt',
    name: 'Holy See',
    ISO3: 'VAT',
    ISO: 'VA',
    independent: true,
    i18nKey: 'countries.vatikanstadt',
  },
  VEN: {
    NAT: 'VEN',
    nameDE: 'Venezuela',
    name: 'Venezuela',
    ISO3: 'VEN',
    ISO: 'VE',
    independent: true,
    i18nKey: 'countries.venezuela',
  },
  ARE: {
    NAT: 'ARE',
    nameDE: 'Vereinigte Arabische Emirate',
    name: 'United Arab Emirates',
    ISO3: 'ARE',
    ISO: 'AE',
    independent: true,
    i18nKey: 'countries.vereinigte-arabische-emirate',
  },
  USA: {
    NAT: 'USA',
    nameDE: 'Vereinigte Staaten von Amerika (USA)',
    name: 'United States of America',
    ISO3: 'USA',
    ISO: 'US',
    independent: true,
    i18nKey: 'countries.usa-vereinigte-staaten-von-amerika',
  },
  VNM: {
    NAT: 'VNM',
    nameDE: 'Vietnam',
    name: 'Viet Nam',
    ISO3: 'VNM',
    ISO: 'VN',
    independent: true,
    i18nKey: 'countries.vietnam',
  },
  WLF: {
    NAT: 'WLF',
    nameDE: 'Wallis und Futuna',
    name: 'Wallis and Futuna',
    ISO3: 'WLF',
    ISO: 'WF',
    independent: false,
    i18nKey: 'countries.wallis-und-futuna',
  },
  CXR: {
    NAT: 'CXR',
    nameDE: 'Weihnachtsinsel',
    name: 'Christmas Island',
    ISO3: 'CXR',
    ISO: 'CX',
    independent: false,
    i18nKey: 'countries.weihnachtsinsel',
  },
  BLR: {
    NAT: 'BLR',
    nameDE: 'Weißrussland',
    name: 'Belarus',
    ISO3: 'BLR',
    ISO: 'BY',
    independent: true,
    i18nKey: 'countries.weissrussland',
  },
  ESH: {
    NAT: 'ESH',
    nameDE: 'Westsahara',
    name: 'Western Sahara',
    ISO3: 'ESH',
    ISO: 'EH',
    independent: false,
    i18nKey: 'countries.westsahara',
  },
  CAF: {
    NAT: 'CAF',
    nameDE: 'Zentralafrika',
    name: 'Central African Republic',
    ISO3: 'CAF',
    ISO: 'CF',
    independent: true,
    i18nKey: 'countries.zentralafrikanische-republik',
  },
  CYP: {
    NAT: 'CYP',
    nameDE: 'Zypern',
    name: 'Cyprus',
    ISO3: 'CYP',
    ISO: 'CY',
    independent: true,
    i18nKey: 'countries.zypern',
  },
} as const
