apiVersion: v1
data:
  MONGODB_URI: {{ .Values.global.mongodb.uri | b64enc }}
kind: Secret
metadata:
  name: mongodb
  labels:
    {{- include "codeanker.label" . | indent 4 }}
type: Opaque
---
apiVersion: v1
data:
  KEY: {{ .Values.api.s3.key | b64enc }}
  SECRET: {{ .Values.api.s3.secret | b64enc }}
  BUCKET: {{ .Values.api.s3.bucket | b64enc }}
  SHARED_BUCKET: {{ .Values.api.s3.sharedBucket | b64enc }}
kind: Secret
metadata:
  name: s3
  labels:
    {{- include "codeanker.label" . | indent 4 }}
type: Opaque
---
apiVersion: v1
data:
  KEY: {{ .Values.api.sendgrid.key | b64enc }}
kind: Secret
metadata:
  name: sendgrid
  labels:
    {{- include "codeanker.label" . | indent 4 }}
type: Opaque
