name: Release Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare:
    name: 🔨 Initialisieren
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.prop }}
      commit: ${{ steps.set-commit.outputs.commit }}
    steps:
    - uses: actions/checkout@v4
    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@v0.2.0
      with:
          path: 'package.json'
          prop_path: 'version'
    - name: set commit
      id: set-commit
      run: echo "commit=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
  release:
    needs: prepare
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: set chart version
        run: |
          sed -i "s/version: .*/version: ${{ needs.prepare.outputs.version }}-${{ needs.prepare.outputs.commit }}/g" chart/brahmsee-digital/Chart.yaml
      - name: set commit in values
        run: |
          sed -i "s/commit: .*/commit: ${{ needs.prepare.outputs.commit }}/g chart/brahmsee-digital/values.yaml"

      - name: pack chart
        run: helm package chart/brahmsee-digital

      - name: upload chart artifact
        uses: actions/upload-artifact@v4
        with:
          path: brahmsee-digital-*.tgz
